import test from 'node:test';
import assert from 'node:assert/strict';
import { build } from 'esbuild';
import { Window } from 'happy-dom';
import { resolve } from 'node:path';
import { createDemoBridge } from '../packages/ui/src/demo';
const bundle = build({ stdin: { contents: "export { mountRemote } from './apps/chrome-extension/src/remote.tsx'; export { act } from 'react';", resolveDir: resolve(process.cwd()), loader: 'tsx' }, bundle: true, write: false, format: 'iife', globalName: 'RemoteUI', platform: 'browser', loader: { '.css': 'empty' }, define: { 'process.env.NODE_ENV': '"development"' } });
test('compact remote reconnects snapshot, separates focus/audio, searches with keyboard-accessible controls and cancels area without writes', async () => {
  const window = new Window({ url: 'http://127.0.0.1/', settings: { enableJavaScriptEvaluation: true, suppressInsecureJavaScriptEnvironmentWarning: true } });
  Object.defineProperty(window, 'MessageChannel', { value: class { port1 = { onmessage: null as null | (() => void) }; port2 = { postMessage: () => window.setTimeout(() => this.port1.onmessage?.(), 0) }; } });
  window.console.timeStamp = () => {};
  Object.assign(window.screen, { availWidth: 1440, availHeight: 900, availLeft: -1440, availTop: 30 });
  const commands: any[] = []; let refuseArea = false;
  (window as any).chrome = { runtime: { sendMessage: async (c: any) => { commands.push(c); return refuseArea && c.type === 'SET_TV_AREA' ? { ok: false, reason: 'Area could not be saved.' } : { ok: true }; } }, permissions: { request: async () => { commands.push('permission'); return false; } } };
  window.eval(`${(await bundle).outputFiles[0].text}\nwindow.RemoteUI = RemoteUI;`);
  window.document.body.innerHTML = '<div id="test-root"></div>';
  const api = (window as any).RemoteUI, bridge = createDemoBridge(), base = await bridge.getSnapshot(), calls: string[] = [];
  bridge.getSnapshot = async () => ({ ...base, mode: 'extension', panes: [{ id: 'main', isMain: true, channelId: base.guide[0].channel.id, channelName: 'Original player', muted: true, volume: .37 }], activePaneId: 'main' });
  bridge.focusPane = async id => { calls.push(`focus:${id}`); return { ok: true }; };
  bridge.selectPane = async id => { calls.push(`audio:${id}`); return { ok: true }; };
  let dispose: () => void = () => {};
  const click = async (text: string) => { const button = [...window.document.querySelectorAll('button')].find(b => b.textContent === text)!; assert(button); await api.act(async () => button.click()); };
  try {
    await api.act(async () => { dispose = api.mountRemote(window.document.getElementById('test-root'), bridge); });
    assert.match(window.document.body.textContent!, /1 \/ 4 feeds/); assert.equal(commands.length, 0);
    await click('Focus feed'); assert.deepEqual(calls, ['focus:main']); await click('Select audio'); assert.deepEqual(calls, ['focus:main', 'audio:main']);
    const search = window.document.querySelector('input[type=search]')!;
    Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype, 'value')!.set!.call(search, 'nonmatching channel');
    await api.act(async () => search.dispatchEvent(new window.Event('input', { bubbles: true })));
    assert.match(window.document.body.textContent!, /No observed matches/); assert.equal([...window.document.querySelectorAll('details')].find(d => d.querySelector('summary')?.textContent === 'Guide / Sports')!.open, true);
    await click('TV area'); assert.equal(window.document.querySelectorAll('input[type=number]').length, 4);
    assert.equal(window.document.activeElement?.textContent, 'This screen');
    assert(window.document.querySelector('[role=dialog]'));
    await click('Cancel'); assert.equal(commands.length, 0);
    assert.equal(window.document.activeElement?.textContent, 'TV area');
    await click('TV area');
    await click('Apply and start workspace');
    assert.deepEqual(commands.map(c => c.command?.type ?? c.type), ['SET_TV_AREA', 'START_WORKSPACE']);
    assert.equal(window.document.querySelector('[role=dialog]'), null); commands.length = 0;
    refuseArea = true; await click('TV area'); await click('Apply and start workspace');
    assert.deepEqual(commands.map(c => c.command?.type ?? c.type), ['SET_TV_AREA']);
    assert(window.document.querySelector('[role=dialog]')); assert.match(window.document.body.textContent!, /Area could not be saved/);
    await click('Cancel'); commands.length = 0; refuseArea = false;
    await click('TV area'); await click('Choose monitor'); assert.deepEqual(commands, ['permission']); assert.match(window.document.body.textContent!, /denied/);
    await click('Cancel'); await api.act(async () => dispose());
    await api.act(async () => { dispose = api.mountRemote(window.document.getElementById('test-root'), bridge); });
    assert.match(window.document.body.textContent!, /Original player/); assert.equal(calls.filter(x => x.startsWith('audio')).length, 1);
  } finally { await api.act(async () => dispose()); await window.happyDOM.abort(); }
});
